"""Seleções: nome PT-BR (Superbet) → nome EN (international_results)."""

COUNTRIES_PT_EN: dict[str, str] = {
    "Brasil": "Brazil",
    "Argentina": "Argentina",
    "Uruguai": "Uruguay",
    "Paraguai": "Paraguay",
    "Chile": "Chile",
    "Colômbia": "Colombia",
    "Peru": "Peru",
    "Equador": "Ecuador",
    "Bolívia": "Bolivia",
    "Venezuela": "Venezuela",
    "México": "Mexico",
    "Estados Unidos": "United States",
    "EUA": "United States",
    "Canadá": "Canada",
    "Costa Rica": "Costa Rica",
    "Panamá": "Panama",
    "Honduras": "Honduras",
    "Jamaica": "Jamaica",
    "El Salvador": "El Salvador",
    "Guatemala": "Guatemala",
    "Nicarágua": "Nicaragua",
    "Haiti": "Haiti",
    "Cuba": "Cuba",
    "Trinidad e Tobago": "Trinidad and Tobago",
    "Curaçao": "Curaçao",
    "Suriname": "Suriname",
    "República Dominicana": "Dominican Republic",
    "Alemanha": "Germany",
    "França": "France",
    "Inglaterra": "England",
    "Escócia": "Scotland",
    "País de Gales": "Wales",
    "Irlanda do Norte": "Northern Ireland",
    "Irlanda": "Republic of Ireland",
    "República da Irlanda": "Republic of Ireland",
    "Espanha": "Spain",
    "Portugal": "Portugal",
    "Itália": "Italy",
    "Países Baixos": "Netherlands",
    "Holanda": "Netherlands",
    "Bélgica": "Belgium",
    "Suíça": "Switzerland",
    "Áustria": "Austria",
    "Croácia": "Croatia",
    "Sérvia": "Serbia",
    "Eslovênia": "Slovenia",
    "Eslováquia": "Slovakia",
    "República Tcheca": "Czech Republic",
    "Tchéquia": "Czech Republic",
    "Polônia": "Poland",
    "Hungria": "Hungary",
    "Romênia": "Romania",
    "Bulgária": "Bulgaria",
    "Grécia": "Greece",
    "Turquia": "Turkey",
    "Türkiye": "Turkey",
    "Dinamarca": "Denmark",
    "Suécia": "Sweden",
    "Noruega": "Norway",
    "Finlândia": "Finland",
    "Islândia": "Iceland",
    "Ilhas Faroé": "Faroe Islands",
    "Estônia": "Estonia",
    "Letônia": "Latvia",
    "Lituânia": "Lithuania",
    "Ucrânia": "Ukraine",
    "Bielorrússia": "Belarus",
    "Rússia": "Russia",
    "Geórgia": "Georgia",
    "Armênia": "Armenia",
    "Azerbaijão": "Azerbaijan",
    "Cazaquistão": "Kazakhstan",
    "Moldávia": "Moldova",
    "Bósnia e Herzegovina": "Bosnia and Herzegovina",
    "Bósnia": "Bosnia and Herzegovina",
    "Montenegro": "Montenegro",
    "Macedônia do Norte": "North Macedonia",
    "Albânia": "Albania",
    "Kosovo": "Kosovo",
    "Chipre": "Cyprus",
    "Malta": "Malta",
    "Luxemburgo": "Luxembourg",
    "Liechtenstein": "Liechtenstein",
    "Andorra": "Andorra",
    "San Marino": "San Marino",
    "Gibraltar": "Gibraltar",
    "Israel": "Israel",
    "Japão": "Japan",
    "Coreia do Sul": "South Korea",
    "Coréia do Sul": "South Korea",
    "Coreia do Norte": "North Korea",
    "China": "China",
    "Austrália": "Australia",
    "Nova Zelândia": "New Zealand",
    "Irã": "Iran",
    "Iraque": "Iraq",
    "Arábia Saudita": "Saudi Arabia",
    "Catar": "Qatar",
    "Qatar": "Qatar",
    "Emirados Árabes Unidos": "United Arab Emirates",
    "Emirados Árabes": "United Arab Emirates",
    "Bahrein": "Bahrain",
    "Omã": "Oman",
    "Kuwait": "Kuwait",
    "Jordânia": "Jordan",
    "Líbano": "Lebanon",
    "Síria": "Syria",
    "Palestina": "Palestine",
    "Uzbequistão": "Uzbekistan",
    "Tajiquistão": "Tajikistan",
    "Quirguistão": "Kyrgyzstan",
    "Turcomenistão": "Turkmenistan",
    "Índia": "India",
    "Tailândia": "Thailand",
    "Vietnã": "Vietnam",
    "Indonésia": "Indonesia",
    "Malásia": "Malaysia",
    "Filipinas": "Philippines",
    "Singapura": "Singapore",
    "Hong Kong": "Hong Kong",
    "Taiwan": "Taiwan",
    "Egito": "Egypt",
    "Marrocos": "Morocco",
    "Argélia": "Algeria",
    "Tunísia": "Tunisia",
    "Líbia": "Libya",
    "Nigéria": "Nigeria",
    "Gana": "Ghana",
    "Senegal": "Senegal",
    "Camarões": "Cameroon",
    "Costa do Marfim": "Ivory Coast",
    "Mali": "Mali",
    "Burkina Faso": "Burkina Faso",
    "Guiné": "Guinea",
    "Guiné-Bissau": "Guinea-Bissau",
    "Guiné Equatorial": "Equatorial Guinea",
    "Cabo Verde": "Cape Verde",
    "Gâmbia": "Gambia",
    "Togo": "Togo",
    "Benin": "Benin",
    "Níger": "Niger",
    "Chade": "Chad",
    "Sudão": "Sudan",
    "Sudão do Sul": "South Sudan",
    "Etiópia": "Ethiopia",
    "Quênia": "Kenya",
    "Uganda": "Uganda",
    "Tanzânia": "Tanzania",
    "Ruanda": "Rwanda",
    "Burundi": "Burundi",
    "RD Congo": "DR Congo",
    "Congo DR": "DR Congo",
    "República Democrática do Congo": "DR Congo",
    "Congo": "Congo",
    "Gabão": "Gabon",
    "Angola": "Angola",
    "Zâmbia": "Zambia",
    "Zimbábue": "Zimbabwe",
    "Moçambique": "Mozambique",
    "Malawi": "Malawi",
    "Namíbia": "Namibia",
    "Botsuana": "Botswana",
    "África do Sul": "South Africa",
    "Madagascar": "Madagascar",
    "Maurício": "Mauritius",
    "Comores": "Comoros",
    "Serra Leoa": "Sierra Leone",
    "Libéria": "Liberia",
    "Mauritânia": "Mauritania",
    "Eswatini": "Eswatini",
    "Lesoto": "Lesotho",
    "Papua-Nova Guiné": "Papua New Guinea",
    "Fiji": "Fiji",
    "Ilhas Salomão": "Solomon Islands",
    "Taiti": "Tahiti",
}

# Códigos FIFA (trigramas) → nome EN canônico. Usados pelo CanonicalEventResolver
# para casar "IRQ x OMA" com "Iraque x Omã" sem depender de similaridade textual.
COUNTRY_CODES: dict[str, str] = {
    "BRA": "Brazil", "ARG": "Argentina", "URU": "Uruguay", "PAR": "Paraguay", "CHI": "Chile", "COL": "Colombia",
    "PER": "Peru", "ECU": "Ecuador", "BOL": "Bolivia", "VEN": "Venezuela", "MEX": "Mexico", "USA": "United States",
    "CAN": "Canada", "CRC": "Costa Rica", "PAN": "Panama", "HON": "Honduras", "JAM": "Jamaica", "SLV": "El Salvador",
    "GUA": "Guatemala", "HAI": "Haiti", "CUB": "Cuba", "TRI": "Trinidad and Tobago", "CUW": "Curaçao", "SUR": "Suriname",
    "GER": "Germany", "FRA": "France", "ENG": "England", "SCO": "Scotland", "WAL": "Wales", "NIR": "Northern Ireland",
    "IRL": "Republic of Ireland", "ESP": "Spain", "POR": "Portugal", "ITA": "Italy", "NED": "Netherlands", "BEL": "Belgium",
    "SUI": "Switzerland", "AUT": "Austria", "DEN": "Denmark", "SWE": "Sweden", "NOR": "Norway", "FIN": "Finland",
    "ISL": "Iceland", "POL": "Poland", "CZE": "Czech Republic", "SVK": "Slovakia", "HUN": "Hungary", "ROU": "Romania",
    "BUL": "Bulgaria", "SRB": "Serbia", "CRO": "Croatia", "SVN": "Slovenia", "BIH": "Bosnia and Herzegovina",
    "MNE": "Montenegro", "MKD": "North Macedonia", "ALB": "Albania", "KOS": "Kosovo", "GRE": "Greece", "TUR": "Turkey",
    "UKR": "Ukraine", "RUS": "Russia", "BLR": "Belarus", "GEO": "Georgia", "ARM": "Armenia", "AZE": "Azerbaijan",
    "KAZ": "Kazakhstan", "LTU": "Lithuania", "LVA": "Latvia", "EST": "Estonia", "MDA": "Moldova", "CYP": "Cyprus",
    "MLT": "Malta", "LUX": "Luxembourg", "LIE": "Liechtenstein", "AND": "Andorra", "SMR": "San Marino", "GIB": "Gibraltar",
    "FRO": "Faroe Islands", "ISR": "Israel", "JPN": "Japan", "KOR": "South Korea", "PRK": "North Korea", "CHN": "China",
    "AUS": "Australia", "NZL": "New Zealand", "IRN": "Iran", "IRQ": "Iraq", "KSA": "Saudi Arabia", "QAT": "Qatar",
    "UAE": "United Arab Emirates", "BHR": "Bahrain", "OMA": "Oman", "KUW": "Kuwait", "JOR": "Jordan", "LBN": "Lebanon",
    "SYR": "Syria", "PLE": "Palestine", "UZB": "Uzbekistan", "TJK": "Tajikistan", "KGZ": "Kyrgyzstan", "TKM": "Turkmenistan",
    "IND": "India", "THA": "Thailand", "VIE": "Vietnam", "IDN": "Indonesia", "MAS": "Malaysia", "PHI": "Philippines",
    "SGP": "Singapore", "HKG": "Hong Kong", "TPE": "Taiwan", "EGY": "Egypt", "MAR": "Morocco", "ALG": "Algeria",
    "TUN": "Tunisia", "LBY": "Libya", "NGA": "Nigeria", "GHA": "Ghana", "SEN": "Senegal", "CMR": "Cameroon",
    "CIV": "Ivory Coast", "MLI": "Mali", "BFA": "Burkina Faso", "GUI": "Guinea", "GNB": "Guinea-Bissau", "EQG": "Equatorial Guinea",
    "CPV": "Cape Verde", "GAM": "Gambia", "TOG": "Togo", "BEN": "Benin", "NIG": "Niger", "CHA": "Chad", "SDN": "Sudan",
    "SSD": "South Sudan", "ETH": "Ethiopia", "KEN": "Kenya", "UGA": "Uganda", "TAN": "Tanzania", "RWA": "Rwanda",
    "BDI": "Burundi", "COD": "DR Congo", "CGO": "Congo", "GAB": "Gabon", "ANG": "Angola", "ZAM": "Zambia", "ZIM": "Zimbabwe",
    "MOZ": "Mozambique", "MWI": "Malawi", "NAM": "Namibia", "BOT": "Botswana", "RSA": "South Africa", "MAD": "Madagascar",
    "MRI": "Mauritius", "COM": "Comoros", "SLE": "Sierra Leone", "LBR": "Liberia", "MTN": "Mauritania", "SWZ": "Eswatini",
    "LES": "Lesotho", "PNG": "Papua New Guinea", "FIJ": "Fiji", "SOL": "Solomon Islands", "TAH": "Tahiti",
}
